name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.19.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          registry-url: https://registry.npmjs.org

      - name: Setup npm
        run: npm install -g npm@11.19.0

      - name: Check versions
        run: |
          node -v
          npm -v
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Show release plan
        run: pnpm version -r --dry-run

      - name: Version packages
        run: pnpm version -r --no-git-checks

      - name: Show package versions
        run: |
          echo "SDK:"
          node -p "require('./packages/sdk/package.json').version"

          echo "Create SDK:"
          node -p "require('./packages/create-sdk/package.json').version"

      - name: Build packages
        run: pnpm -r build

      - name: Publish sdk
        working-directory: packages/sdk
        run: npm publish --access public --tag beta

      - name: Publish create-sdk
        working-directory: packages/create-sdk
        run: npm publish --access public --tag beta

      - name: Commit and push release
        run: |
          VERSION=$(node -p "require('./packages/sdk/package.json').version")

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git commit -m "chore: release v${VERSION}"

          git tag "v${VERSION}"

          git push origin HEAD:${GITHUB_REF_NAME}
          git push origin "v${VERSION}"

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(node -p "require('./packages/sdk/package.json').version")

          gh release create "v${VERSION}" \
            --title "v${VERSION}" \
            --generate-notes
